### PR TITLE
Switch lib/jbuild to S-expression syntax

### PR DESCRIPTION
**Pull request by diml**
It looks nicer and fixes this issue: https://github.com/janestreet/jbuilder/issues/399

### CODE REVIEW

**Comment by rgrinberg** [comment]
@mjambon would you mind merging this and making a release?

**Comment by rgrinberg** [comment]
@diml curious as to why you didn't use `${version:yojson}` here.

**Comment by diml** [comment]
True, I just mechanically updated the code

**Comment by diml** [comment]
Done

**Comment by rgrinberg** [comment]
Martin Jambon <notifications@github.com> writes:

> Merged #50.

Thank you Martin. If possible, a release would be nice. We'd like to get
rid of as much ocaml syntax in opam as possible.

**Comment by mjambon** [comment]
This will be in cppo 1.6.3 https://github.com/ocaml/opam-repository/pull/11465

**Pull request merged**
